services:
  ai-service:
    build: ./AI_service
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - ./AI_service:/app
    stdin_open: true
    tty: true

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    
    volumes:
      - ollama_data:/root/.ollama
    
    restart: unless-stopped
  
volumes:
  ollama_data: